# Generated by Django 5.1 on 2024-10-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
    ]
